data <- read.table('household_power_consumption.txt', sep = ';', header = TRUE)
data <-mutate(data, Date = as.Date(Date, format = '%d/%m/%Y'))
data <- select(data, Date, Global_active_power)
d1 <- subset(data, Date == '2007-02-01')
d2 <- subset(data, Date == '2007-02-02')
data <- as.data.frame(rbind(d1,d2))
rm(d1)
rm(d2)
data <- mutate(data, GAP = as.numeric(Global_active_power) /1000)
hist(data$GAP, xlab = 'Global Active Power (kilowatts)', main ='Global Active Power', col = 'red')
dev.copy(png, file = 'plot1.png')
dev.off()